logging.file.name=logs/roomescape.log
logging.logback.rollingpolicy.file-name-pattern=logs/roomescape-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB